Repository houtanf/Unsupervised-KNN-JS, pull requests merged in 2019-09, with the labels that each got.

#12 Feature/cosine distance
  README.md
  native/src/distances/distance_algos.rs
  native/src/distances/mod.rs
  native/src/distances/vector_utils.rs
  package-lock.json
  package.json
  tests/distance_tests/euclidean.test.js
  tests/knn.test.js
Labels: enhancement

#13 Fix/windows install
  .travis.yml
Labels: bug

#14 Fix/node versions
  .travis.yml
  tests/knn.test.js
Labels: bug

#15 Feature/extra distance metrics
  CHANGELOG.md
  README.md
  native/Cargo.lock
  native/Cargo.toml
  native/src/distances/distance_algos.rs
  native/src/knn_utils/distance_computation.rs
  native/src/knn_utils/knn.rs
  native/src/lib.rs
  package-lock.json
  package.json
  tests/knn.test.js
Labels: documentation, enhancement

#17 sum_of_sqrd_diff, mae, L10
  .travis.yml
  CHANGELOG.md
  README.md
  native/src/distances/distance_algos.rs
  package.json
  tests/knn.test.js
Labels: enhancement

#18 Optimization/get k
  CHANGELOG.md
  native/src/knn_utils/knn.rs
  package-lock.json
  package.json
Labels: enhancement
